# Generated by Django 4.1.3 on 2022-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_work_delete_slider_alter_country_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('question', models.CharField(max_length=900)),
                ('answer', models.CharField(max_length=900)),
            ],
        ),
    ]
